name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: nmake -f Makefile.Win
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ONScripter-Jh
        path: D:/ONScripter-Jh
